'use client';
import { useEffect, useState } from 'react';
import { supabase } from './lib_supabase';
import './style.css';

export default function App(){
 const [session,setSession]=useState(null); const [email,setEmail]=useState(''); const [sent,setSent]=useState(false); const [screen,setScreen]=useState('home'); const [profile,setProfile]=useState({display_name:'',age:'',city:'',bio:''}); const [msg,setMsg]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>data.subscription.unsubscribe()},[]);
 async function login(e){e.preventDefault(); setMsg(''); const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}}); if(error)setMsg(error.message); else setSent(true)}
 async function saveProfile(){if(!session)return; const {error}=await supabase.from('profiles').upsert({id:session.user.id,display_name:profile.display_name,age:profile.age?Number(profile.age):null,city:profile.city,bio:profile.bio},{onConflict:'id'}); if(error)setMsg(error.message); else setScreen('need')}
 if(!session) return <main className="shell"><header><b>humanly</b><span>real human connection</span></header><section className="hero"><div className="eyebrow">MVP</div><h1>Real people.<br/>Real connection.</h1><p>You don't have to explain everything. Just tell us what kind of connection you could use right now.</p>{!sent?<form onSubmit={login}><input type="email" required placeholder="Your email" value={email} onChange={e=>setEmail(e.target.value)}/><button>Continue</button></form>:<div className="notice">Check your email for your Humanly sign-in link.</div>}{msg&&<div className="error">{msg}</div>}</section></main>;
 return <main className="shell"><header><b>humanly</b><button className="ghost" onClick={()=>supabase.auth.signOut()}>Sign out</button></header>
 {screen==='home'&&<><section><h1>What do you need right now?</h1><p>You don't have to know exactly what you need.</p><button className="card" onClick={()=>setScreen('need')}><strong>🫶 I want some connection</strong><small>Talk, walk, share an activity, or simply have company.</small></button><button className="card" onClick={()=>setScreen('available')}><strong>🤝 I'm available to connect</strong><small>I have some time and would like to connect.</small></button></section></>}
 {screen==='profile'&&<section><button className="back" onClick={()=>setScreen('home')}>← Back</button><h1>Your profile</h1><p>Keep it simple. You can change this later.</p>{[['display_name','Name'],['age','Age'],['city','City']].map(([k,l])=><input key={k} placeholder={l} value={profile[k]} onChange={e=>setProfile({...profile,[k]:e.target.value})}/>)}<textarea placeholder="A little about you" value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})}/><button onClick={saveProfile}>Continue</button></section>}
 {screen==='need'&&<section><button className="back" onClick={()=>setScreen('home')}>← Back</button><h1>What kind of connection would help?</h1><p>Select anything that sounds right.</p><div className="tags">{['💬 Talk','👂 Someone to listen','☕ Coffee','🚶 Walk','🎮 Play','🎨 Hobby','💻 Virtual company','🌍 Meet someone new'].map(x=><button key={x} className="tag">{x}</button>)}</div><button onClick={()=>setScreen('matches')}>Find people</button></section>}
 {screen==='matches'&&<section><button className="back" onClick={()=>setScreen('need')}>← Change request</button><h1>People available now</h1><p>These are example matches for the MVP. Real availability comes next.</p>{['Mia, 34 · Copenhagen','Jonas, 41 · Roskilde'].map((x,i)=><div className="profile" key={x}><b>{x}</b><small>{i?'Danish / English · Talk · Walk':'English · Talk · Creative hobbies'}</small><p>“Happy to have a relaxed conversation about pretty much anything.”</p><button onClick={()=>setScreen('connection')}>Connect</button></div>)}</section>}
 {screen==='available'&&<section><button className="back" onClick={()=>setScreen('home')}>← Back</button><h1>I'm available 🤝</h1><p>Let people know you have time for a human connection.</p><div className="tags">{['💬 Talk','👂 Listen','🚶 Walk','☕ Coffee','🎮 Gaming','💻 Virtual company'].map(x=><button key={x} className="tag">{x}</button>)}</div><button onClick={()=>setScreen('live')}>Become available</button></section>}
 {screen==='live'&&<section><h1>You're available 🟢</h1><p>People looking for connection can now find you.</p><div className="notice"><b>Available now</b><br/><small>Conversation · 30 minutes · Online</small></div><button onClick={()=>setScreen('connection')}>Preview connection</button><button className="secondary" onClick={()=>setScreen('home')}>Stop being available</button></section>}
 {screen==='connection'&&<section><button className="back" onClick={()=>setScreen('home')}>← End</button><h1>You're connected 🫶</h1><p>This is a private connection room.</p><div className="chat"><div className="bubble">Hi! Glad we matched. How's your evening going?</div><div className="bubble mine">Pretty good. I just felt like talking to someone.</div></div><input placeholder="Write a message…"/><button onClick={()=>setScreen('feedback')}>End connection</button></section>}
 {screen==='feedback'&&<section><h1>How did that connection feel?</h1><p>Your feedback is private and helps us keep Humanly safe.</p><div className="tags">{['🙂 Good','😐 Okay','🙁 Not good'].map(x=><button className="tag" key={x}>{x}</button>)}</div><button onClick={()=>setScreen('home')}>Done</button></section>}
 </main>
}
